import { chromium } from "playwright";
import sharp from "sharp";
// unselected anchor icon lives on the 13A frame; others on d13 (already 2x)
const pg = await (await chromium.launch()).newPage({ viewport: { width: 1980, height: 1160 }, deviceScaleFactor: 2 });
await pg.goto("https://www.figma.com/proto/Whv6FPNemFhi5egktiTWFn/x?node-id=19452-12558&scaling=contain&hide-ui=1", { waitUntil: "domcontentloaded", timeout: 45000 });
await pg.waitForTimeout(7000);
const box = await pg.locator("canvas").first().boundingBox();
const W = 1920, H = 1080;
const s = Math.min(box.width / W, box.height / H);
const ox = box.x + (box.width - W * s) / 2, oy = box.y + (box.height - H * s) / 2;
const full = await pg.screenshot({ clip: { x: ox, y: oy, width: W * s, height: H * s } });
await sharp(full).toFile("harvest/full2x/d13a.png");
const px = s * 2;
const cut = (name, src, cx) => sharp(src).extract({ left: Math.round((cx-26)*px), top: Math.round(160*px), width: Math.round(52*px), height: Math.round(52*px) }).png().toFile(`public/assets/ui/${name}.png`);
await cut("ic-anchor", "harvest/full2x/d13a.png", 783);
await cut("ic-uwide", "harvest/full2x/d13.png", 901);
await cut("ic-3d", "harvest/full2x/d13.png", 1019);
await cut("ic-side", "harvest/full2x/d13.png", 1138);
console.log("icons ok");
process.exit(0);
